### PR TITLE
Huge changeset

### PR DESCRIPTION
**Pull request by ProfFan**

### CODE REVIEW

**Comment by Germanunkol** [comment]
Hi,
Even with this patch applied, I still get the error
"[ERROR] [1531089449.122894692]: Can't assign material Triangle List Marker0Material to the ManualObject Triangle List Marker0 because this Material does not exist in group General. Have you forgotten to define it in a .material script?"
... when trying to receive and display a TRIANGLE_LIST (other marker types work fine).
I assume this has to do with the jump from Ogre 1.10 to Ogre 1.11, because you mention a similar error [here](https://github.com/ros-visualization/rviz/pull/1252).

If you need me to, I can try to set up a minimal working example in the next couple of days.

I'm on Arch Linux, where the patch by fizyr-forks is already in the repository:
https://aur.tuna.tsinghua.edu.cn/packages/ros-melodic-rviz/

As far as I know, your patch is not in there yet, so I manually edited the PKGBUILD to get the source from your repo (ProfFan:melodic-devel) and it still gave me the above error.

**Comment by ProfFan** [comment]
@Germanunkol Absolutely yes! I am also on Arch and my branch so you just need to send me your rviz-related files IMHO.

**Comment by de-vri-es** [comment]
Right, I should get on with reviewing this, apologies. I'll try to find time soon :tm:.

**Comment by Germanunkol** [comment]
When trying to recreate the issue above, I noticed it's not as bad as I thought - I do get the Error about not being able to assign a material, but the program keeps running and my object is displayed - just not with the color I tried to assign it.
Tested with the most recent commit on this repo (18a3897b876b6ac609d5de7f521e492fdfcfdb8c).

Steps to reproduce:
1. Install ros-melodic-rviz from yaourt
        In the PKGBUILD, replace source=("${_dir}"::"git+https://github.com/fizyr-forks/rviz.git#branch=ogre1.11")
        with source=("${_dir}"::"git+https://github.com/ProfFan/rviz.git#branch=melodic-devel")
2. Run roscore and rviz, add a "Marker" Display in rviz
3. Download, compile and run the test package: [test_rviz.zip](https://github.com/fizyr-forks/rviz/files/2182020/test_rviz.zip) It's heavily based on the [Basic Shapes Tutorial](http://wiki.ros.org/rviz/Tutorials/Markers%3A%20Basic%20Shapes) but publishes a TRIANGLE_LIST (with two triangles forming a square) instead of one of the more simple shapes.

Rviz will show the triangles in the standard white (should be green) and prints out the error:

    [ERROR] [1531261189.082634464]: Can't assign material Triangle List Marker0Material to the ManualObject Triangle List Marker0 because this Material does not exist in group General. Have you forgotten to define it in a .material script?

Note that other markers (visualization_msgs::Marker::CUBE for example) work fine.

**Comment by ProfFan** [comment]
@Germanunkol Actually that is what I want to say :) It is running OK, but due to the drastic changes in Ogre, it is really hard to fix all that... I am also really busy on other projects recently (-_-.)

**Pull request closed without merging**
